source 'https://rubygems.org'
ruby '2.1.5'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.2.0'
gem 'thin'
gem 'pg'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

source 'https://rails-assets.org' do
  gem 'rails-assets-bootstrap', '~> 3.1.1'
  gem 'rails-assets-font-awesome', '~> 4.3.0'
  gem 'rails-assets-ionicons', '~> 2.0.1'
  gem 'rails-assets-select2', '~> 3.4.5'
  gem 'rails-assets-messenger', '~> 1.4.2'
  gem 'rails-assets-jquery-minicolors', '~> 2.1.12'
  gem 'rails-assets-jquery-flot', '~> 0.8.3'
  gem 'rails-assets-flot.tooltip', '~> 0.8.3'
  gem 'rails-assets-animate-css', '~> 3.3.0'
  gem 'rails-assets-moment', '~> 2.5.1'
  gem 'rails-assets-bootstrap-switch', '~> 3.1.0'
  gem 'rails-assets-bootstrap-datepicker', '~> 1.4.0'
  gem 'rails-assets-bootstrap-daterangepicker', '~> 1.3.6'
end

group :development do
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'quiet_assets'
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :production do
  gem 'rails_log_stdout',           github: 'heroku/rails_log_stdout'
  gem 'rails3_serve_static_assets', github: 'heroku/rails3_serve_static_assets'
  gem 'rails_12factor'
end

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
